config/routes.rb
Rails.application.routes.draw do

  root 'styles#index'

  namespace :stripe do
    post :webhook
  end

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :product_sets do
    get :export
    resources :styles do
      resources :attachments
      put :update_status
      post :duplicate
    end
  end

  resources :styles, only: :index

  resources :categories
  resources :companies

  namespace :api do
    namespace :v1 do
      get '/attachments/:id' => 'attachments#show'
    end
  end

  get '/settings' => 'settings#index'

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }
  namespace :users do
    resources :profile_config, only: :update
  end

  namespace :settings do
    resources :users
  end

  get 'contact', to: 'contact#show', as: 'contact'

end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :product_set
  enum status: [ :created, :pending, :placed, :received, :cancelled, :deleted ]
  INCOMPLETE_STATUSES = [0,1]

  has_many :attachments, dependent: :destroy
  validates :vendor_style_number, presence: true

  scope :open, -> { where(status: [0,1,2,3]) } #ignores cancelled and deleted

  scope :incomplete, -> { where(status: Style::INCOMPLETE_STATUSES) }

  scope :with_value, -> { where(
                      "quantity > ? AND
                      (wholesale_cost > ? OR negotiated_cost > ?) AND
                      retail_price > ?", 0, 0, 0, 0) }

  def initial_mark_up
      return 0 if retail_price.blank? || wholesale_or_negotiated_cost.nil?
      ((retail_price - wholesale_or_negotiated_cost) / retail_price) * 100
  end

  def self.to_csv
    attributes = %w{Vendor_Style_Number Quantity Status Color Created
                        Negotiated_Cost Retail_Price Wholesale_Cost Category_Name Delivery_Date Notes Attachments}

    CSV.generate(headers: true) do |csv|
        csv << attributes
        all.each do |style|
          csv << [
              style.vendor_style_number,
              style.quantity,
              style.status,
              style.color,
              style.created_at.strftime("%Y-%m-%d"),
              style.negotiated_cost,
              style.retail_price,
              style.wholesale_cost,
              style.category_name,
              style.delivery_date,
              style.notes,
              style.attachments.map{ |a| Rails.application.routes.url_helpers.api_v1_url(a) }.join(' ')
            ]
        end
    end
  end

  def wholesale_or_negotiated_cost
    return 0 unless negotiated_cost || wholesale_cost
    negotiated_cost.present? ? negotiated_cost : wholesale_cost
  end

  def default_photo(size = 'large')

    return nil unless attachments.any?
    if default_attachment_id
      a = attachments.find_by_id(default_attachment_id)
      unless a.nil?
        a.photo.url(size)
      end
    else
      attachments.first.photo.url(size)
    end

  end

  # Called from Delayed Job
  def upload_attachments(photos)
    if photos.present?
      photos.each do |photo|
        attachments.create(photo: photo)
      end
    end
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :render_styles_index_or_welcome, only: :index
  before_action :fetch_product_set, except: :index

  def index
    @styles = StyleFinderService.new(params, current_company).perform
  end

   def create
    @style = @product_set.styles.create(style_params.except(:photos) )
    @style.upload_attachments(params[:style][:photos])

    redirect_to product_set_path(@product_set)
   end

   def new
    @style = Style.new
    @product_set = ProductSet.find(params[:product_set_id])

  end

  def edit
    @style = @product_set.styles.find(params[:id])
    @inline = params[:inline]
  end

  def update
    @style = Style.find(params[:id])
    @style.update(style_params)

    if params[:inline] == 'true'
      redirect_to product_set_path(@product_set)
    else
      redirect_to product_set_style_path(@product_set, @style)
    end
  end

  def show
    @style = @product_set.styles.find(params[:id])
  end

  def destroy
    @product_set.styles.find(params[:id]).destroy
    redirect_to product_set_path(@product_set)
  end

  #remote true, looking for update_status.js.erb
  def update_status
    @style = @product_set.styles.find(params[:style_id])
    @style.update(style_params)
  end

  #TODO: non REST-ful route. Can refactor
  def duplicate
    @duplicate_style = StyleDuplicatorService.new(params[:style_id]).perform
    redirect_to product_set_path(@product_set)

  end

  private
    def render_styles_index_or_welcome
      render :welcome unless user_signed_in?
    end

    def fetch_product_set
      @product_set = ProductSet.find(params[:product_set_id])
    end

    def style_params
      params.require(:style).permit(:name, :category_name, :vendor_style_number, :wholesale_cost,
                    :negotiated_cost, :retail_price, :delivery_date, :quantity, :notes, :status,
                    :color, :exclusive, :default_attachment_id, :photos => [])
    end

end

app/helpers/styles_helper.rb
module StylesHelper

  def scout_date_sort_link(params)
    params = params.merge({sort_by: :scout_date, sort_direction: sort_direction})

    link_to "Scout Date #{sort_arrow}".html_safe, styles_path(params)
  end

  def delivery_date_sort_link(params)
    params = params.merge({sort_by: :delivery_date, sort_direction: sort_direction})

    link_to "Delivery Date #{sort_arrow}".html_safe, styles_path(params)
  end

  def sort_direction
    case params[:sort_direction]
      when 'ASC'
        'DESC'
      when 'DESC'
        'ASC'
      else
        'ASC'
    end
  end

  def sort_arrow
    if sort_direction == 'ASC'
      content_tag :span, nil, class: "caret"
    else
      content_tag :span, class: "dropup" do
        content_tag :span, nil, class: "caret"
      end
    end
  end

  # DELIVERY MONTHS AND YEARS
  def options_for_delivery_month_picker(params)
    html_months = "<option value=\"null\"> --- </option>"
    12.times do |i|
      month = i+1
      html_months += content_tag(:option, value: month, selected: current_or_active_delivery_month(params, month)) do
        Date::MONTHNAMES[month]
      end
    end
    return html_months.html_safe
  end

  def options_for_delivery_year_picker(params)
    html_years = "<option value=\"null\"> --- </option>"
    years = (Date.current.year-1)..(Date.current.year+4)
    years.each do |year|
      html_years += content_tag(:option, value: year, selected: current_or_active_delivery_year(params, year)) do
        year.to_s
      end
    end
    return html_years.html_safe
  end

  def current_or_active_delivery_month(params, month)
    if params[:filters].present?
      if params[:filters][:delivery_month] == month.to_s
        return 'selected'
      elsif params[:filters][:delivery_month] == '---'
        return 'selected'
      end
    else
      return 'selected' if month == '---'
    end
  end

  def current_or_active_delivery_year(params, year)
    if params[:filters].present?
      if params[:filters][:delivery_year] == year.to_s
        return 'selected'
      elsif params[:filters][:delivery_year] == '---'
        return 'selected'
      end
    else
      return 'selected' if year == '---'
    end
  end

# SCOUT MONTHS AND YEARS
  def options_for_scout_month_picker(params)
    html_months = "<option value=\"null\"> --- </option>"
    12.times do |i|
      month = i+1
      html_months += content_tag(:option, value: month, selected: current_or_active_scout_month(params, month)) do
        Date::MONTHNAMES[month]
      end
    end
    return html_months.html_safe
  end

  def options_for_scout_year_picker(params)
    html_years = "<option value=\"null\"> --- </option>"
    years = (Date.current.year-1)..(Date.current.year+4)
    years.each do |year|
      html_years += content_tag(:option, value: year, selected: current_or_active_scout_year(params, year)) do
        year.to_s
      end
    end
    return html_years.html_safe
  end

  def current_or_active_scout_month(params, month)
    if params[:filters].present?
      if params[:filters][:scout_month] == month.to_s
        return 'selected'
      elsif params[:filters][:scout_month] == '---'
        return 'selected'
      end
    else
      return 'selected' if month == '---'
    end
  end

  def current_or_active_scout_year(params, year)
    if params[:filters].present?
      if params[:filters][:scout_year] == year.to_s
        return 'selected'
      elsif params[:filters][:scout_year] == '---'
        return 'selected'
      end
    else
      return 'selected' if year == '---'
    end
  end

end

app/views/shared/styles/_edit_buttons.html.haml
.div.dropdown
  %button.btn-sm.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", type: "button"}
    %i.fa.fa-wrench
    %span.fa.fa-caret-down
  %ul#style-edit-dropdown.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1"}
    %li.even
      = link_to product_set_style_duplicate_path(product_set, style), method: :post do
        %i.fa.fa-files-o
        %span Duplicate
    %li.odd
      = link_to edit_product_set_style_path(product_set, style, inline: inline), remote: true  do
        %i.fa.fa-pencil
        %span Edit
    %li.even
      = link_to product_set_style_path(product_set, style), method: :delete, data: {confirm: "Delete style: #{style.vendor_style_number}?"}  do
        %i.fa.fa-trash-o
        %span Delete

app/views/shared/styles/_filters.html.haml
.row
  .col-md-12
    .well#filters
      = form_tag styles_path, method: :get do
        .row.form-group
          .col-md-3
            %label Product Set Name
            = select_tag '[filters][product_set_name]',                                    |
              options_for_select(ProductSet.all.map(&:name).insert(0, ['---', nil]).uniq, |
                params[:filters].try(:[], :product_set_name)),                              |
              class: 'form-control'
          .col-md-3
            %label Status
            = select_tag '[filters][status]',                                            |
              options_for_select(Style.statuses.map{ |key, value| [key.titleize, value]} |
                .insert(0, ['---', nil]),                                                |
                params[:filters].try(:[], :status)), class: 'form-control'               |
          .col-md-3
            %label Style Number
            = text_field_tag '[filters][vendor_style_number]',
              params[:filters].try(:[], :vendor_style_number), class: 'form-control'
          .col-md-3
            %label Buyer
            = select_tag '[filters][user_id]', |
              options_for_select(current_company.users.map{|u| [u.name, u.id]}.insert(0, ['---', nil]).uniq, |
               params[:filters].try(:[], :user_id)), |
              class: 'form-control'
        .row.form-group
          .col-md-3
            %label Scout Year
            = select_tag '[filters][scout_year]', |
              options_for_select(options_for_scout_year_picker(params), |
                params[:filters].try(:[], :scout_year)), |
              class: 'form-control'
          .col-md-3
            %label Scout Month
            = select_tag '[filters][scout_month]', |
              options_for_select(options_for_scout_month_picker(params), |
                params[:filters].try(:[], :scout_month)), |
              class: 'form-control'
          .col-md-3
            %label Delivery Year
            = select_tag '[filters][delivery_year]', |
              options_for_select(options_for_delivery_year_picker(params), |
                params[:filters].try(:[], :delivery_year)), |
              class: 'form-control'
          .col-md-3
            %label Delivery Month
            = select_tag '[filters][delivery_month]', |
              options_for_select(options_for_delivery_month_picker(params), |
                params[:filters].try(:[], :delivery_month)), |
              class: 'form-control'

        .row
          .col-md-6
            = link_to 'Reset Filters', styles_path, class: 'btn btn-default'
          .col-md-6
            = submit_tag 'Filter', class: 'btn btn-primary pull-right'

app/views/shared/styles/_form.html.erb
<%- if params[:action] == "new" %>
  <div class="row form-group">
    <%= form.file_field :photo, type: 'file', class: 'hidden'%>
    <div class="ghost-photo-input-group hidden">
      <label class="btn btn-success btn-file btn-block text-center">
        <i class="fa fa-plus" style="font-size: 30px;"></i><br>
        Add Photo <input type="file" name="style[photos][]" style="display: none;">
      </label>
      <img src="" style=''/>
    </div>
    <div class="col-sm-12 photo-upload-fields">
      <div class="photo-input-group">
        <label class="btn btn-success btn-file btn-block text-center">
          <i class="fa fa-plus" style="font-size: 30px;"></i><br>
          Add Photo <input type="file" name="style[photos][]" style="display: none;">
        </label>
        <img src="" style=''/>
      </div>
    </div>
  </div>
<% end %>

<div class="row form-group">
    <div class="col-sm-6">
        <label>Vendor Style Number</label>
        <%= form.text_field :vendor_style_number, class: 'form-control', :required => true %>
    </div>
    <div class="col-sm-6">
        <label>Wholesale Cost</label>
        <%= form.number_field :wholesale_cost, step: '.01', placeholder: '26.99', :class => 'form-control' %>
    </div>
</div>

<div class='form-group'>
    <a href="#demo" data-toggle="collapse">Additional Fields</a>
</div>
<div id='demo', class="collapse">
    <div class="row form-group">
        <div class="col-sm-2">
            <label>Quantity</label>
            <%= form.number_field :quantity, step: '1', placeholder: '150', :class => 'form-control' %>
        </div>
        <div class="col-sm-4">
            <label>Negotiated Cost</label>
            <%= form.number_field :negotiated_cost, step: '.01', placeholder: '25.01', :class => 'form-control' %>
        </div>
        <div class="col-sm-4">
            <label>Retail Price</label>
            <%= form.number_field :retail_price, step: '.01', placeholder: '100.00', :class => 'form-control' %>
        </div>
        <div class="col-sm-2">
            <label>IMU:</label>
            <div id="imu-data-display">
                N/A
            </div>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-6">
            <label>Status</label>
            <%= form.select :status, options_for_select(Style.statuses.map{ |k,v| [k.humanize, k] }, @style.status), { }, class: 'form-control' %>
        </div>
        <div class="col-sm-6">
            <label>Delivery Date</label>
            <%= form.text_field :delivery_date, :class => 'form-control' %>
        </div>
    </div>
    <div class="row form-group">

        <div class="col-sm-4">
            <label>Exclusive?</label>
            <%= form.check_box :exclusive %>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-6">
            <label>Color</label>
            <%= form.text_field :color, :class => 'form-control' %>
        </div>
        <div class="col-sm-6">
            <label>Category</label>
            <%= form.select :category_name, options_for_select( Category.all.map{ |c| [c.display_name, c.name ] }, @style.category_name), { }, class: 'form-control' %>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-sm-12">
            <label>Notes</label>
            <%= form.text_area :notes, :class => 'form-control' %>
        </div>
    </div>
</div><!-- collapse container -->


<div class="row">
    <div class="form-group col-md-12">
        <%= form.submit 'Submit Style', class: 'btn btn-primary btn-submit btn-block'%>
    </div>
    <div class="col-md-12">
        <%= link_to "Cancel", product_set_path(@product_set)%>
    </div>
</div>

<script>
  $(document).ready(function() {
    $( "#style_delivery_date" ).datepicker({
      dateFormat: "yy-mm-dd"
    });

    bind_imu_calculator();

  }); //end document ready
</script>