config/routes.rb
Rails.application.routes.draw do

  root 'styles#index'

  namespace :stripe do
    post :webhook
  end

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :product_sets do
    get :export
    resources :styles do
      resources :attachments
      put :update_status
      post :duplicate
    end
  end

  resources :styles, only: :index

  resources :categories
  resources :companies

  namespace :api do
    namespace :v1 do
      get '/attachments/:id' => 'attachments#show'
    end
  end

  get '/settings' => 'settings#index'

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }
  namespace :users do
    resources :profile_config, only: :update
  end

  namespace :settings do
    resources :users
  end

  get 'contact', to: 'contact#show', as: 'contact'

end

app/models/category.rb
class Category < ActiveRecord::Base
  before_save :downcase_name

  def display_name
    name.titleize
  end

  private
    def downcase_name
        self.name = name.downcase
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def create
    Category.create(category_params)
    redirect_to settings_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update( name:params["category"]["name"] )
    redirect_to settings_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to settings_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

end

app/views/shared/categories/_edit.html.erb
  <%= form_for @category, url: category_path(@category), method: :put do |f| %>
    <h3>Edit Category</h3>
    <hr class="style4" style="margin: 5px 0 5px 0">
    <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= link_to "Delete", category_path(@category), class: "btn btn-default", method: :delete %>
        <%= f.submit "Update", class: "btn btn-primary pull-right"%>
      </div>
  <% end %>

app/views/shared/categories/_index.html.erb
<div class="row">
  <div class="col-sm-6">
    <ul class="list-group">
        <%- @categories.each do |c| %>
            <li class="list-group-item">
                <%= link_to c.display_name, edit_category_path(c), remote: true %>
            </li>
        <% end %>
    </ul>
  <div>
    <%= link_to "Add New Category", new_category_path, class: 'btn btn-default', remote: true %>
  </div>
  </div>
  <div class="col-sm-6">
    <div id="form-container">
      <!-- this container gets stuff dynamically from javascript like edit and new -->
    </div>
  </div>
</div>

app/views/shared/categories/_new.html.erb
  <%= form_for category, url: categories_path, method: :post do |f| %>
    <h3>New Category</h3>
    <hr class="style4" style="margin: 5px 0 5px 0">
    <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.submit "Create", class: "btn btn-primary" %>
      </div>
  <% end %>