config/routes.rb
Rails.application.routes.draw do

  root 'styles#index'

  namespace :stripe do
    post :webhook
  end

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :product_sets do
    get :export
    resources :styles do
      resources :attachments
      put :update_status
      post :duplicate
    end
  end

  resources :styles, only: :index

  resources :categories
  resources :companies

  namespace :api do
    namespace :v1 do
      get '/attachments/:id' => 'attachments#show'
    end
  end

  get '/settings' => 'settings#index'

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }
  namespace :users do
    resources :profile_config, only: :update
  end

  namespace :settings do
    resources :users
  end

  get 'contact', to: 'contact#show', as: 'contact'

end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :product_set
  enum status: [ :created, :pending, :placed, :received, :cancelled, :deleted ]
  INCOMPLETE_STATUSES = [0,1]

  has_many :attachments, dependent: :destroy
  validates :vendor_style_number, presence: true

  scope :open, -> { where(status: [0,1,2,3]) } #ignores cancelled and deleted

  scope :incomplete, -> { where(status: Style::INCOMPLETE_STATUSES) }

  scope :with_value, -> { where(
                      "quantity > ? AND
                      (wholesale_cost > ? OR negotiated_cost > ?) AND
                      retail_price > ?", 0, 0, 0, 0) }

  def initial_mark_up
      return 0 if retail_price.blank? || wholesale_or_negotiated_cost.nil?
      ((retail_price - wholesale_or_negotiated_cost) / retail_price) * 100
  end

  def self.to_csv
    attributes = %w{Vendor_Style_Number Quantity Status Color Created
                        Negotiated_Cost Retail_Price Wholesale_Cost Category_Name Delivery_Date Notes Attachments}

    CSV.generate(headers: true) do |csv|
        csv << attributes
        all.each do |style|
          csv << [
              style.vendor_style_number,
              style.quantity,
              style.status,
              style.color,
              style.created_at.strftime("%Y-%m-%d"),
              style.negotiated_cost,
              style.retail_price,
              style.wholesale_cost,
              style.category_name,
              style.delivery_date,
              style.notes,
              style.attachments.map{ |a| Rails.application.routes.url_helpers.api_v1_url(a) }.join(' ')
            ]
        end
    end
  end

  def wholesale_or_negotiated_cost
    return 0 unless negotiated_cost || wholesale_cost
    negotiated_cost.present? ? negotiated_cost : wholesale_cost
  end

  def default_photo(size = 'large')

    return nil unless attachments.any?
    if default_attachment_id
      a = attachments.find_by_id(default_attachment_id)
      unless a.nil?
        a.photo.url(size)
      end
    else
      attachments.first.photo.url(size)
    end

  end

  # Called from Delayed Job
  def upload_attachments(photos)
    if photos.present?
      photos.each do |photo|
        attachments.create(photo: photo)
      end
    end
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :render_styles_index_or_welcome, only: :index
  before_action :fetch_product_set, except: :index

  def index
    @styles = StyleFinderService.new(params, current_company).perform
  end

   def create
    @style = @product_set.styles.create(style_params.except(:photos) )
    @style.upload_attachments(params[:style][:photos])

    redirect_to product_set_path(@product_set)
   end

   def new
    @style = Style.new
    @product_set = ProductSet.find(params[:product_set_id])

  end

  def edit
    @style = @product_set.styles.find(params[:id])
    @inline = params[:inline]
  end

  def update
    @style = Style.find(params[:id])
    @style.update(style_params)

    if params[:inline] == 'true'
      redirect_to product_set_path(@product_set)
    else
      redirect_to product_set_style_path(@product_set, @style)
    end
  end

  def show
    @style = @product_set.styles.find(params[:id])
  end

  def destroy
    @product_set.styles.find(params[:id]).destroy
    redirect_to product_set_path(@product_set)
  end

  #remote true, looking for update_status.js.erb
  def update_status
    @style = @product_set.styles.find(params[:style_id])
    @style.update(style_params)
  end

  #TODO: non REST-ful route. Can refactor
  def duplicate
    @duplicate_style = StyleDuplicatorService.new(params[:style_id]).perform
    redirect_to product_set_path(@product_set)

  end

  private
    def render_styles_index_or_welcome
      render :welcome unless user_signed_in?
    end

    def fetch_product_set
      @product_set = ProductSet.find(params[:product_set_id])
    end

    def style_params
      params.require(:style).permit(:name, :category_name, :vendor_style_number, :wholesale_cost,
                    :negotiated_cost, :retail_price, :delivery_date, :quantity, :notes, :status,
                    :color, :exclusive, :default_attachment_id, :photos => [])
    end

end

app/helpers/styles_helper.rb
module StylesHelper

  def scout_date_sort_link(params)
    params = params.merge({sort_by: :scout_date, sort_direction: sort_direction})

    link_to "Scout Date #{sort_arrow}".html_safe, styles_path(params)
  end

  def delivery_date_sort_link(params)
    params = params.merge({sort_by: :delivery_date, sort_direction: sort_direction})

    link_to "Delivery Date #{sort_arrow}".html_safe, styles_path(params)
  end

  def sort_direction
    case params[:sort_direction]
      when 'ASC'
        'DESC'
      when 'DESC'
        'ASC'
      else
        'ASC'
    end
  end

  def sort_arrow
    if sort_direction == 'ASC'
      content_tag :span, nil, class: "caret"
    else
      content_tag :span, class: "dropup" do
        content_tag :span, nil, class: "caret"
      end
    end
  end

  # DELIVERY MONTHS AND YEARS
  def options_for_delivery_month_picker(params)
    html_months = "<option value=\"null\"> --- </option>"
    12.times do |i|
      month = i+1
      html_months += content_tag(:option, value: month, selected: current_or_active_delivery_month(params, month)) do
        Date::MONTHNAMES[month]
      end
    end
    return html_months.html_safe
  end

  def options_for_delivery_year_picker(params)
    html_years = "<option value=\"null\"> --- </option>"
    years = (Date.current.year-1)..(Date.current.year+4)
    years.each do |year|
      html_years += content_tag(:option, value: year, selected: current_or_active_delivery_year(params, year)) do
        year.to_s
      end
    end
    return html_years.html_safe
  end

  def current_or_active_delivery_month(params, month)
    if params[:filters].present?
      if params[:filters][:delivery_month] == month.to_s
        return 'selected'
      elsif params[:filters][:delivery_month] == '---'
        return 'selected'
      end
    else
      return 'selected' if month == '---'
    end
  end

  def current_or_active_delivery_year(params, year)
    if params[:filters].present?
      if params[:filters][:delivery_year] == year.to_s
        return 'selected'
      elsif params[:filters][:delivery_year] == '---'
        return 'selected'
      end
    else
      return 'selected' if year == '---'
    end
  end

# SCOUT MONTHS AND YEARS
  def options_for_scout_month_picker(params)
    html_months = "<option value=\"null\"> --- </option>"
    12.times do |i|
      month = i+1
      html_months += content_tag(:option, value: month, selected: current_or_active_scout_month(params, month)) do
        Date::MONTHNAMES[month]
      end
    end
    return html_months.html_safe
  end

  def options_for_scout_year_picker(params)
    html_years = "<option value=\"null\"> --- </option>"
    years = (Date.current.year-1)..(Date.current.year+4)
    years.each do |year|
      html_years += content_tag(:option, value: year, selected: current_or_active_scout_year(params, year)) do
        year.to_s
      end
    end
    return html_years.html_safe
  end

  def current_or_active_scout_month(params, month)
    if params[:filters].present?
      if params[:filters][:scout_month] == month.to_s
        return 'selected'
      elsif params[:filters][:scout_month] == '---'
        return 'selected'
      end
    else
      return 'selected' if month == '---'
    end
  end

  def current_or_active_scout_year(params, year)
    if params[:filters].present?
      if params[:filters][:scout_year] == year.to_s
        return 'selected'
      elsif params[:filters][:scout_year] == '---'
        return 'selected'
      end
    else
      return 'selected' if year == '---'
    end
  end

end

app/views/styles/_add_photo.html.haml
= form_for :attachment, url: product_set_style_attachments_path(@product_set, @style), method: :post do |f|
  = f.file_field :photo, type: 'file', class: 'hidden'
  .col-md-4
    .well.photo-upload-well
      .ghost-photo-input-group.hidden
        %label.btn.btn-success.btn-file.btn-block
          Add photo
          %input{type:'file', name: 'style[photos][]', style: 'display: none'}
        %img{src:'#'}
      .row
        .col-sm-12.photo-upload-fields
          .photo-input-group
            %label.btn.btn-success.btn-file.btn-block{style: 'margin-bottom: 15px;'}
              Add photo
              %input{type:'file', name: 'style[photos][]', style: 'display: none'}
            %img{src:'#'}
      .row
        .col-sm-6
          = f.submit 'Upload', class: 'btn btn-primary'
        .col-sm-6.text-right
          = link_to 'Cancel', product_set_style_path()

app/views/styles/_edit_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header modal-header-primary">
      Edit Style: <%= @style.vendor_style_number %>
    </div>
    <div class="modal-body">
      <%= form_for @style, url: product_set_style_path(@product_set, @style), method: :put do |f| %>
        <%= hidden_field_tag "inline", @inline %>
        <%= render partial: 'shared/styles/form', locals: {form: f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/styles/edit.js.erb
$('#modal').html("<%= j(render partial: 'styles/edit_form', locals: {product_set: @product_set, style: @style} ) %> ").modal('show');

app/views/styles/index.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        All Styles
      .panel-body
        .form-group
          %button.btn.btn-default{"data-target" => "#filterContainer", "data-toggle" => "collapse"}
            %i.fa.fa-filter
            Filters
        #filterContainer{class: ('collapse' unless params[:filters].present?)}
          = render partial: 'shared/styles/filters'
      %hr#style-index-line/
      .hidden-xs
        %table.table
          %thead
            %tr
              %th
              %th Style Number
              %th Product Set
              %th Status
              %th Buyer
              %th
                = scout_date_sort_link(params)
              %th
                = delivery_date_sort_link(params)
              %th Markup
              %th Cost
              %th Retail Price
              %th
          %tbody
            - @styles.each do |style|
              %tr{:id => "style-id-#{style.id}"}
                %td.text-center
                  - if style.default_photo
                    = link_to product_set_style_attachments_path(style.product_set.id, style), remote: true do
                      = image_tag style.default_photo('square'), style:'width:60px;'
                  - else
                    \--
                %td
                  = link_to style.vendor_style_number, product_set_style_path(style.product_set, style)
                %td
                  = link_to "#{style.product_set.name}", product_set_path(style.product_set.id)
                %td
                  = form_for style, url: product_set_style_update_status_path(style.product_set_id, style), method: :put, remote: true do |f|
                    = hidden_field_tag :authenticity_token, form_authenticity_token
                    = f.select :status, options_for_select( Style.statuses.map{ |k,v| [k.humanize, k] }, style.status), { }, onchange: "$(this.form).submit();", class: 'form-control'
                    = f.submit ' ', class: "hidden"
                %td
                  = style.product_set.user.name
                %td
                  - if style.product_set.scout_date.present?
                    = style.product_set.scout_date.strftime('%b %e, %Y')
                  - else
                    N/A
                %td
                  - if style.delivery_date.present?
                    = style.delivery_date.strftime('%b %e, %Y')
                  - else
                    N/A
                %td
                  = number_to_percentage style.initial_mark_up, precision: 2
                %td
                  = number_to_currency style.wholesale_cost, precision: 2
                %td
                  = number_to_currency style.retail_price, precision: 2
                %td.text-right
      / end
      .visible-xs
        - @styles.each do |style|
          .panel-body
            .well
              - if style.default_photo
                = link_to product_set_style_attachments_path(style.product_set.id, style), remote: true do
                  = image_tag style.default_photo('square'), style:'width:60px;'
              - else
                \--
              = link_to product_set_style_path(style.product_set, style) do
                = "Style: #{style.vendor_style_number}&nbsp;".html_safe
              %br
              = link_to product_set_path(style.product_set.id) do
                = "Product Set: #{style.product_set.name}"
    = will_paginate(@styles)

    - if @styles.empty?
      .row
        .col-md-6.col-md-offset-3
          = link_to new_product_set_path, remote: true, class: "btn btn-primary btn-block btn-lg" do
            ADD PRODUCT SET

app/views/styles/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="">
        <div class="modal-header">
          New style for product_set: <%= @product_set.name %>
        </div>
        <div class="panel-body">
          <%= form_for @style, url: product_set_styles_path(@product_set), multipart: true, method: :post, html: { class: 'ui-form' } do |f| %>
            <%= render partial: 'shared/styles/form', locals: {form: f} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/styles/show.html.haml
.panel.panel-default
  %ul.panel-heading.breadcrumb.clearfix
    %li= link_to @product_set.name, product_set_path(@product_set)
    %li.active= @style.vendor_style_number
    %span.pull-right
      %li= render partial: "shared/styles/edit_buttons", locals: {product_set: @product_set, style: @style, inline: false}
  .panel-body
    .row.form-group
      .col-sm-3
        - if @style.default_photo
          = image_tag @style.default_photo, style: "max-height: 100%; max-width: 100%;"
        - else
          %i.fa.fa-file-image-o.fa-5x{ style: "padding: 65px;"}
      .col-sm-9
        = form_for @style, url: product_set_style_path(@product_set, @style), method: :put do |f|
          .row
            .col-md-4
              .form-group
                %label Style Number:
                = f.text_field :vendor_style_number, class: 'form-control'
              .form-group
                %label Status:
                = f.select :status, options_for_select(Style.statuses.map{ |k,v| [k.humanize, k] }, @style.status), { }, class: 'form-control'
              .form-group
                %label Exclusive:
                = f.check_box :exclusive
            .col-md-4
              .form-group
                %label Wholesale Cost:
                = f.text_field :wholesale_cost, class: 'form-control'
              .form-group
                %label Negotiated Cost:
                = f.text_field :negotiated_cost, class: 'form-control'
              .form-group
                %label Retail Price:
                = f.text_field :retail_price, class: 'form-control'
              .form-group
                %label Quantity:
                = f.text_field :quantity, class: 'form-control'
              .form-group
                %label IMU:
                %strong#imu-data-display
                  = number_to_percentage @style.initial_mark_up, precision: 2
            .col-md-4
              .form-group
                %label Color:
                = f.text_field :color, class: 'form-control'
              .form-group
                %label Delivery Date:
                = f.text_field :delivery_date, class: 'form-control'
          .row.form-group
            .col-md-12
              %label Notes:
              = f.text_area :notes, class: 'form-control', rows: 5
          .row
            .col-md-12
              = f.submit 'Update', class: 'btn btn-primary'

.row
  - @style.attachments.each do |attachment|
    .col-md-2
      .well
        = link_to product_set_style_attachments_path(@product_set, @style), remote: true do
          = image_tag attachment.photo.url('square'), :style=>'display: block; margin: auto; max-width:100%;'
        = link_to 'Delete', product_set_style_attachment_path(@product_set, @style, attachment), |
          data: {confirm: 'Delete attachment?'}, method: :delete                                      |
        |
        \#{link_to 'Make Default', product_set_style_path(@product_set, @style, style: {default_attachment_id: attachment.id}), method: :put}

  = render 'styles/add_photo'



:javascript
  $(document).ready(function() {
    bind_imu_calculator();

    $( "#style_delivery_date" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
  })

app/views/styles/update_status.js.erb
$("#style-id-<%=@style.id %>").addClass('update-style-success <%= @style.status %>');

setTimeout(function(){
  $("#style-id-<%=@style.id %>").removeClass('update-style-success <%= @style.status %>');
},2000)